# Generated by Django 4.2.20 on 2025-03-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='customer',
        ),
    ]
