# Generated by Django 4.2.20 on 2025-03-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_user_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieuxuat',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('completed', 'Hoàn thành'), ('canceled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
