# Generated by Django 4.2.20 on 2025-04-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_phieunhap_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
