# Generated by Django 4.2.20 on 2025-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhacungcap',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
