# Generated by Django 4.2.20 on 2025-04-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_nhacungcap_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieunhap',
            name='codeKho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.kho', to_field='code'),
        ),
    ]
