# Generated by Django 4.2.20 on 2025-04-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_phieunhap_codekho'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.TextField(blank=True),
        ),
    ]
