# Generated by Django 4.2.20 on 2025-04-15 21:21

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhacungcap',
            name='code',
            field=models.CharField(default=database.models.generate_unique_code, max_length=20, unique=True),
        ),
    ]
