# Generated by Django 4.2.20 on 2025-04-15 21:26

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_nhacungcap_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default=database.models.generate_unique_code, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='addressNCC',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='code',
            field=models.CharField(default=database.models.generate_unique_code, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='emailNCC',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='nameNCC',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='phoneNCC',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='phieunhap',
            name='code',
            field=models.CharField(default=database.models.generate_unique_code, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='phieunhap',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('completed', 'Hoàn thành'), ('canceled', 'Đã hủy')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='phieuxuat',
            name='code',
            field=models.CharField(default=database.models.generate_unique_code, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='phieuxuat',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('completed', 'Hoàn thành'), ('canceled', 'Đã hủy')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=database.models.generate_unique_code, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
